name: Linkspector

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  check-links:
    if: github.event.pull_request.draft == false
    name: linkspector
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Resolve "No usable sandbox" error
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          level: any
          config_file: .github/settings/.linkspector.yml
